[project]
name = "asynchronous-payment-processing-service"
version = "0.1.0"
description = "Asynchronous payment processing service"
readme = "README.md"
requires-python = ">=3.14,<4.0"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic>=2.0",
    "pydantic-settings",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "psycopg[binary]",
    "alembic",
    "faststream[rabbit]",
    "httpx",
    "aio-pika (>=10.0.1,<11.0.0)",
]

[dependency-groups]
dev = [
    "ruff",
]


[tool.ruff]
line-length = 100
target-version = "py314"


[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
]


[tool.ruff.format]
quote-style = "double"
